apiVersion: v2
appVersion: 1.7.0
dependencies:
- name: nms-hybrid
  repository: https://github.com/nginxinc/helm-charts/stable
  version: ~2.11.0
- condition: global.nmsModules.nms-acm.enabled
  name: nms-acm
  repository: https://github.com/nginxinc/helm-charts/stable
  version: ~1.6.0
#- name: nms-adm
#  repository: https://github.com/nginxinc/helm-charts/stable
#  version: ~4.0.0
description: A chart for installing the NGINX Management Suite
name: nms
type: application
version: 1.7.0