# BIG-IP Credentials
BIGIPhost01: "calalang-azure-0.westus2.cloudapp.azure.com"
BIGIPadminUsername: "admin"
BIGIPadminPassword: "Harrison123!"

# BIG-IP Provider for BIG-IP Modules
bigips: ["{{ BIGIPhost01 }}"]
bigip_provider:
  server: "{{ item }}"
  user: "{{ BIGIPadminUsername }}"
  password: "{{ BIGIPadminPassword }}"
  validate_certs: false