apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nms.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
data:
  nms.conf: |-
{{ tpl ( .Files.Get "files/nms.conf" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nms.nginx.http.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
data:
  nms-http.conf: |-
{{ tpl ( .Files.Get "generated/nms-http.conf" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nms.nginx.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ tpl ( .Files.Get "generated/nginx.conf" ) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nms.openid.config.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
data:
  openid_configuration.conf: |
{{ tpl ( .Files.Get "files/openid_configuration.conf" ) . | indent 4 }}
  openid_connect.conf: |
{{ tpl ( .Files.Get "files/openid_connect.conf" ) . | indent 4 }}
---