kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http-snippets: |
    keyval_zone zone=custom-zone:10m timeout=5m; # Maintain recent client info for 5m
    keyval $request_uri $custom_variable zone=custom-zone; # Key=requested uri, Value=custom variable
  stream-snippets: |
    server {
        listen 12345;
        listen [::]:12345;
        zone_sync;
        zone_sync_server nginx-ingress-headless.nginx-ingress.svc.cluster.local:12345 resolve;
    }
  resolver-addresses: 10.0.8.10
  resolver-valid: 5s
  http2: "true"