apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: prometheus
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: readystatus
  type: ClusterIP
  selector:
    app: nginx-ingress-nginx-ingress