# NGINX Application Services

# Create NGINX Resources through {{ NMShost01 }}

- name: Verify NGINX Instance Manager {{ NMShost01 }} is Available
  delegate_to: localhost
  uri:
    headers:
      token: "{{ NMSToken }}"
    force_basic_auth: yes
    url_password: "{{ NMSadminPassword }}"
    url_username: "{{ NMSadminUsername }}"
    method: GET
    url: "https://{{ NMShost01 }}/api/platform/v1/instances"
    status_code: 200
    validate_certs: yes
  register: nms_instance_response
  retries: 30
  delay: 5
  until: "(nms_instance_response is successful) and (nms_instance_response.status == 200)"
  when: state == "present"

# - name: Prepare the Common AS3 Declaration
#   template: src="../../f5-automation-toolchain/as3/bigip-common.template" dest="../../f5-automation-toolchain/as3/bigip-common.json"
#   delegate_to: localhost
#   when: state == "present"
# 
# - name: Create or update {{BIGIPhost01}}; Common AS3 Declaration
#   delegate_to: localhost
#   uri:
#     body: "{{ lookup('file','../../f5-automation-toolchain/as3/' + 'bigip-common.json') }}"
#     body_format: json
#     headers:
#       X-F5-Auth-Token: "{{ bigip1_auth_token }}"
#     method: POST
#     status_code: [200, 202]
#     url: "https://{{BIGIPhost01}}/mgmt/shared/appsvcs/declare"
#     validate_certs: no
#     timeout: "60"
#   register: result
#   retries: 30
#   delay: 5
#   until: "(result.status == 200) or (result.status == 202)"
#   when: state == "present"