apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: terraform
  labels:
    app: nginx-service
spec:
  ports:
  - name: http
    port: ${nginx_port}
  selector:
    app: nginx-deployment
  type: ClusterIP