# NGINX ingress repository JWT

apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress

---

apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: nginx-ingress
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${nginx_repo_jwt}