# NGINX service and deployment

apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx-service
spec:
  ports:
  - name: http
    port: ${nginx_port}
  selector:
    app: nginx-deployment
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ${nginx_image}
        ports:
        - containerPort: 80