apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-bin
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-bin
  template:
    metadata:
      labels:
        app: http-bin
    spec:
      containers:
      - env:
        - name: http-bin
          value: http-bin
        image: kennethreitz/httpbin
        imagePullPolicy: Always
        name: http-bin
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-bin
  namespace: default
spec:
  ports:
  - name: http-bin
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: http-bin