## F5 AI Gateway configuration
## Ref: https://aigateway.clouddocs.f5.com/installation/install-with-helm.html#configuration
##

# Port for the service
aigw.service.port: 80

# Port for the service
processors.f5.service.port: 80

# Enable the core (aigw) application
aigw.enabled: true

# Type of services for the service
aigw.service.type: "ClusterIP"

# Security context for the aigw deployment
aigw.securityContext:
  # fsGroup: 1001
  # runAsGroup: 1001
  runAsNonRoot: true
  # runAsUser: 1001
  seccompProfile: { "type": "RuntimeDefault" }

# Security context for the aigw-processors-f5 deployment
processors.f5.securityContext:
  # fsGroup: 1001
  # runAsGroup: 1001
  runAsNonRoot: true
  # runAsUser: 1001
  seccompProfile: { "type": "RuntimeDefault" }
