## F5 AI Gateway configuration
## Ref: https://aigateway.clouddocs.f5.com/installation/install-with-helm.html#configuration
##

# Port for the service
aigw.service.port: 8000

# Port for the service
processors.f5.service.port: 8001

# Enable the core (aigw) application
aigw.enabled: true

# Type of services for the service
aigw.service.type: "ClusterIP"

# Security context for the aigw deployment

aigw.securityContext:
  {
    "runAsNonRoot": true,
    "seccompProfile": { "type": "RuntimeDefault" },
  }
