apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "calalang-net/dataguard-alarm"
    securityLog:
      enable: true
      apLogConf: "logconf"
      logDest: "syslog:server=syslog.syslog-svc.default:514"
