apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: kubernetes.calalang.net
spec:
  ingressClassName: nginx
  host: kubernetes.calalang.net
  tls:
    secret: kubernetes-calalang-net-tls-secret
    redirect:
      enable: true
  upstreams:
    - name: spa
      service: spa
      port: 80
    - name: spa-dark
      service: spa-dark
      port: 80
    - name: api
      service: api
      port: 8000
      healthCheck:
        enable: true
        path: /api/stats
        interval: 20s
        jitter: 3s
        port: 8000
    - name: inventory
      service: inventory
      port: 8002
    - name: recommendations
      service: recommendations
      port: 8001
  routes:
    - path: /
      #      policies:
      #        - name: kubernetes-calalang-net-oidc-policy
      action:
        proxy:
          upstream: spa
          responseHeaders:
            add:
              - name: IC-Nginx-Version
                value: ${nginx_version}
                always: true
              - name: IC-Nginx-Host
                value: ${host}
                always: true
              - name: IC-Nginx-URI
                value: ${request_uri}
                always: true
              - name: IC-Nginx-Server-Address
                value: ${server_addr}
                always: true
    - path: /api
      location-snippets: |
        set $custom_variable $binary_remote_addr;
      #      policies:
      #        - name: brewz-rate-limit-policy
      #        - name: brewz-api-policy
      action:
        proxy:
          upstream: api
      errorPages:
        - codes: [404]
          return:
            code: 404
            type: application/json
            body: |
              {\"msg\": \"Could not find the resource!\"}
            headers:
              - name: x-debug-original-status
                value: ${upstream_status}
    - path: /api/inventory
      #      policies:
      #        - name: brewz-api-policy
      action:
        proxy:
          upstream: inventory
          rewritePath: /api/inventory
    - path: /api/recommendations
      #      policies:
      #        - name: brewz-api-policy
      action:
        proxy:
          upstream: recommendations
          rewritePath: /api/recommendations
    - path: /images
      #      policies:
      #        - name: brewz-api-policy
      action:
        proxy:
          upstream: api
          rewritePath: /images
    - path: /status
      action:
        return:
          code: 200
          type: "text/plain"
          body: "Hello from ${server_addr}\n"
#      policies:
#        - name: brewz-waf-policy
