apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nms.core.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nms.core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nms.core.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ template "nms.serviceAccountName" . }}
      initContainers:
        {{- include "nms.core.initContainers" . | nindent 8 }}
      containers:
        - name: core
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.core.container.port.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.core.container.port.grpc }}
              protocol: TCP
          env:
            # Clickhouse env variable
            {{- include "nms.clickhouse.env" . | nindent 12 }}
            # core specific env variable
            {{- include "nms.core.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.dpm.resources | nindent 12 }}
          volumeMounts:
            - name: nms-conf-volume
              mountPath: /etc/nms/nms.conf
              subPath: nms.conf
            - name: nms-modules-volume
              mountPath: /var/lib/nms/modules.json
              subPath: modules.json
            - name: certs
              mountPath: /etc/nms/certs
              readOnly: true
            {{- include "nms.core.userVolumeMounts" . | nindent 12 }}
      volumes:
        - name: nms-conf-volume
          configMap:
            defaultMode: 0644
            name: {{ template "nms.config.name" . }}
        - name: nms-modules-volume
          configMap:
            defaultMode: 0644
            name: {{ template "nms.modules.name" . }}
        - name: certs
          projected:
            sources:
              - secret:
                  name: {{ template "nms.secret.internal-certs.name" . }}
                  items:
                    - key: ca.pem
                      path: services/ca.pem
                    - key: core-server.pem
                      path: services/core-server.pem
                    - key: core-server.key
                      path: services/core-server.key
                    - key: core-client.pem
                      path: services/core-client.pem
                    - key: core-client.key
                      path: services/core-client.key
        {{- include "nms.core.userVolumes" . | nindent 8 }}