apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nms.secret.auth.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  auth: admin:{{ template "nms.admin-pwd" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nms.secret.internal-certs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: "Opaque"
data:
  {{- include "nms.gen-internal-certs" . | nindent 2 }}
---
{{- if not .Values.apigw.tlsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nms.secret.apigw-certs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nms.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: "kubernetes.io/tls"
data:
  {{- include "nms.gen-apigw-certs" . | nindent 2 }}
{{- end }}