# NGINX Application Services

# Create Configuration In NGINX One Tenant

- name: Verify NGINX One is Available
  delegate_to: localhost
  uri:
    headers:
      Authorization: "{{ nginx-one-f5xc-api-token }}"
    method: GET
    url: "https://{{ nginx-one-f5xc-tenant }}.console.ves.volterra.io/api/nginx/one/namespaces/default/instances/summary"
    status_code: 200
    validate_certs: yes
  register: nginx_one_instances_summary_response
  retries: 30
  delay: 5
  until: "(nginx_one_instances_summary_response is successful) and (nginx_one_instances_summary_response.status == 200)"
  when: state == "present"

- name: Template NGINX One azure-instances Cluster Declaration
  template: src="../config/azure-instances/nginx.tpl" dest="../config/azure-instances/nginx.json"
  delegate_to: localhost
  when: state == "present"

- name: Create or update NGINX One azure-instances Cluster Declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('ansible.builtin.file','../config/azure-instances/nginx.json') }}"
    body_format: json
    headers:
      Authorization: "{{ nginx-one-f5xc-api-token }}"
    method: PUT
    url: "https://{{ nginx-one-f5xc-tenant }}.console.ves.volterra.io/api/nginx/one/namespaces/default/instances/{{ item }}/config"
    status_code: [200, 202]
    validate_certs: yes
  register: nginx_one_instance_group_put_response
  retries: 30
  delay: 5
  until: "(result.status == 200) or (result.status == 202)"
  with_items:
    - azure_instances
  when: state == "present"
