apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: nms
type: nginx.org/oidc
data:
  client-secret: M2VjZDU2MWQtNzBhNy00MzkxLTkwYjMtZTY2ODAzYmYzMmZk
# client-secret is base64encoded