apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nms.calalang.net
  namespace: nms
spec:
  ingressClassName: nginx
  host: nms.calalang.net
  tls:
    secret: nms-apigw-certs
    redirect:
      enable: true
  upstreams:
  - name: apigw
    service: apigw
    port: 443
    type: http
    tls:
      enable: true
  routes:
  - path: /ui
    location-snippets: |
      status_zone nms-server;
    policies:
    - name: oidc-policy
    action:
      proxy:
        upstream: apigw
  - path: /
    location-snippets: |
      status_zone nms-server;
    action:
      proxy:
        upstream: apigw