apiVersion: v1
kind: Secret
metadata:
  name: open-webui-calalang-net-oidc-secret
type: nginx.org/oidc
data:
  client-secret: NVlhOFF+YlpBV0ttMjJ2STFlc0YyVDZ3MXJZNnpmU2xrZUtKNmFDVA==
# client-secret the "value" object and is base64encoded
