# automation toolchain specific parameters
tmp_dir: "/home/runner"
f5_networks_github_base_url: "https://api.github.com/repos/F5Networks"

as3_file: "as3.rpm"
as3_file_sha256: "{{as3_file}}.sha256"
as3_use_latest: true
as3_requested_tag: "v3.47.0" # a default value that is used if not overidden and if as3_use_latest = false

do_file: "do.rpm"
do_file_sha256: "{{do_file}}.sha256"
do_use_latest: true
do_requested_tag: "v1.40.0" # a default value that is used if not overidden and if do_use_latest = false

ts_file: "ts.rpm"
ts_file_sha256: "{{ts_file}}.sha256"
ts_use_latest: true
ts_requested_tag: "v1.33.0" # a default value that is used if not overidden and if ts_use_latest = false

fast_file: "fast.rpm"
fast_file_sha256: "{{fast_file}}.sha256"
fast_use_latest: true
fast_requested_tag: "v1.24.0" # a default value that is used if not overidden and if ts_use_latest = false

cfe_file: "cfe.rpm"
cfe_file_sha256: "{{cfe_file}}.sha256"
cfe_use_latest: true
cfe_requested_tag: "v1.15.0" # a default value that is used if not overidden and if ts_use_latest = false