# BIG-IP Access Profiles

# Create BIG-IP {{BIGIPhost01}} Resources

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Import System Auth APM policy
  bigip_apm_policy_import:
    name: system-auth
    source: ../files/system-auth.tar.gz
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Import OIDC APM policy
  bigip_apm_policy_import:
    name: calalang-oidc
    source: ../files/calalang-odic.tar.gz
    force: yes
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Import Webtop APM policy
  bigip_apm_policy_import:
    name: calalang-webtop
    source: ../files/calalang-webtop.tar.gz
    force: yes
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Import System AWS Federation policy
  bigip_apm_policy_import:
    name: aws-federation
    source: ../files/aws-federation.tar.gz
    force: yes
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"