apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "open-webui"
  namespace: argocd
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com/
    targetRevision: ${open_webui_chart_version}
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/open-webui/helm-charts/refs/heads/main/charts/open-webui/values.yaml
      ignoreMissingValueFiles: false
      parameters:
        - name: "pipelines.enabled"
          value: "false"
        - name: "websocket.enabled"
          value: "false"
      values: |
        extraEnvVars:
          - name: WEBUI_URL
            value: "https://open-webui.calalang.net"
          - name: CORS_ALLOW_ORIGIN
            value: "https://open-webui.calalang.net"
  destination:
    name: "in-cluster"
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
