apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-config
data:
  app.conf: |-
    server {
      listen 8443 ssl;

      server_name ingresslink.calalang.net;

      ssl_certificate /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;

      default_type text/plain;

      location / {
        return 200 "Welcome through Ingresslink you are at TLS server name $ssl_server_name, you reached pod $hostname. You got here at $date_local!\n" ;
      }
    }