project: default
source:
  repoURL: 'https://github.com/jmcalalang/lab'
  path: nginx-management-suite/nms-hybrid
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: nms
syncPolicy:
  automated: {}
  syncOptions:
    - Replace=true
