apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
type: nginx.org/oidc
data:
  client-secret: ZkJwOFF+Yld5QWNaWUVqZXh+cDFWTWdBbFljLnVLVko5NllDM2J+SQ==
# client-secret the "value" object and is base64encoded