apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
type: nginx.org/oidc
data:
  client-secret: RlFlOFF+eS10Q2lmdm9kelVfSy1nRHotY2xRV0luWVNUbnlmbmJhNA==
# client-secret the "value" object and is base64encoded