---
-
  hosts: localhost
  roles:
    - ../roles/provision-modules
    - ../roles/install-atc
    - ../roles/access-profiles
    - ../roles/application-services-3
    - ../roles/partitions
    - ../roles/telemetry-streaming