apiVersion: v1
kind: Service
metadata:
  name: nginx-plus-container
  namespace: nginx-plus
  labels:
    app: nginx-plus-container
spec:
  ports:
  - name: http
    port: 80
  - name: api
    port: 8080
  - name: redis
    port: 6379
  selector:
    app: nginx-plus-container
  type: ClusterIP