apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unprivileged
  namespace: ${namespace}
  labels:
    app: nginx-unprivileged
spec:
  selector:
    matchLabels:
      app: nginx-unprivileged
  template:
    metadata:
      labels:
        app: nginx-unprivileged
    spec:
      containers:
        - name: nginx-unprivileged
          image: nginxinc/nginx-unprivileged:${nginx-unprivileged-version}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080