apiVersion: v1
kind: Service
metadata:
  name: nginx-unprivileged
  namespace: ${namespace}
spec:
  type: ClusterIP
  selector:
    app: nginx-unprivileged
  ports:
    - name: http
      port: 80
      targetPort: 8080