apiVersion: v1
kind: Service
metadata:
  name: {{ template "acm.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ template "acm.serviceHttpPort" . }}
      protocol: TCP
      name: acm-api
  selector:
    {{- include "acm.selectorLabels" . | nindent 4 }}
