apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ingresslink.calalang.net
  namespace: ingresslink
spec:
  ingressClassName: ingresslink-nginx
  host: ingresslink.calalang.net
  tls:
    secret: kubernetes-calalang-net-tls-secret
    redirect:
      enable: true
  upstreams:
  - name: http-bin
    service: http-bin
    port: 80
  routes:
  - path: /
    location-snippets: |
      status_zone root;
    policies:
    - name: oidc-policy
    action:
      proxy:
        upstream: http-bin