apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: ingresslink
type: kubernetes.io/dockerconfigjson
data:
  username: ${nginx_repo_jwt}
  password: none
  server: private-registry.nginx.com