apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: grpc.argo.calalang.net
  namespace: argocd
spec:
  ingressClassName: nginx
  host: grpc.argo.calalang.net
  tls:
    secret: argo-calalang-net-tls-secret
  upstreams:
  - name: argo-argocd-server
    service: argo-argocd-server
    port: 443
    type: grpc
    tls:
      enable: true
  routes:
  - path: /
    location-snippets: |
      status_zone argo-calalang-net-root;
    action:
      pass: argo-argocd-server