apiVersion: v1
kind: Secret
metadata:
  name: onlineboutique
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  type: helm
  url: us-docker.pkg.dev/online-boutique-ci/charts
