# BIG-IP Provision Modules

# Create BIG-IP {{BIGIPhost01}} Resources

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision Management
  bigip_provision:
    module: mgmt
    memory: 2048
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision AFM
  bigip_provision:
    module: afm
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision LTM
  bigip_provision:
    module: ltm
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision AVR
  bigip_provision:
    module: avr
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision GTM
  bigip_provision:
    module: gtm
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision FPS
  bigip_provision:
    module: fps
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision ASM
  bigip_provision:
    module: asm
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"

- name: Provision APM
  bigip_provision:
    module: apm
    level: nominal
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"
  when: state == "present"