{
  "tenant_name": "fast-http",
  "app_name": "fast-http-application",
  "virtual_address": "192.168.1.100",
  "virtual_port": 443,
  "fastl4": false,
  "enable_redirect": true,
  "enable_snat": true,
  "snat_automap": true,
  "enable_persistence": true,
  "use_existing_persistence_profile": false,
  "persistence_type": "cookie",
  "enable_fallback_persistence": false,
  "enable_tls_server": true,
  "make_tls_server_profile": true,
  "tls_cert_name": "/Common/default.crt",
  "tls_key_name": "/Common/default.key",
  "enable_tls_client": false,
  "enable_pool": true,
  "make_pool": true,
  "use_static_members": true,
  "pool_members": [
    {
      "serverAddresses": [
        "192.168.1.101"
      ],
      "servicePort": 80,
      "connectionLimit": 0,
      "priorityGroup": 0,
      "shareNodes": true
    }
  ],
  "use_sd": true,
  "service_discovery": [
    {
      "sd_type": "event",
      "sd_port": 80
    }
  ],
  "load_balancing_mode": "least-connections-member",
  "slow_ramp_time": 300,
  "enable_monitor": true,
  "make_monitor": true,
  "monitor_interval": 30,
  "monitor_credentials": false,
  "monitor_send_string": "GET / HTTP/1.1\\r\\nHost: example.com\\r\\nConnection: Close\\r\\n\\r\\n",
  "monitor_expected_response": "",
  "make_http_profile": true,
  "x_forwarded_for": true,
  "enable_acceleration": true,
  "make_acceleration_profile": true,
  "enable_compression": true,
  "make_compression_profile": true,
  "enable_multiplex": true,
  "make_multiplex_profile": true,
  "common_tcp_profile": false,
  "make_tcp_ingress_profile": true,
  "tcp_ingress_topology": "wan",
  "make_tcp_egress_profile": true,
  "tcp_egress_topology": "lan",
  "endpoint_policy_names": [],
  "irule_names": [],
  "vlans_enable": false,
  "enable_analytics": false,
  "enable_waf_policy": false,
  "enable_asm_bot_defense": false,
  "enable_asm_logging": true,
  "log_profile_names": [],
  "enable_telemetry": false,
  "monitor_timeout": "91",
  "asm": true,
  "ts": true
}