apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ingresslink.calalang.net
  namespace: calalang-net
spec:
  ingressClassName: ingresslink-nginx
  host: ingresslink.calalang.net
  tls:
    secret: kubernetes-calalang-net-tls-secret
    redirect:
      enable: true
  upstreams:
  - name: www-nginx-org-externalname
    service: www-nginx-org-externalname
    port: 80
  routes:
  - path: /
    policies:
    - name: oidc-policy
    location-snippets: |
      status_zone externalname;
      set $custom_variable $remote_addr; 
    action:
      proxy:
        upstream: www-nginx-org-externalname
        rewritePath: /
        requestHeaders:
          set:
            - name: Host
              value: nginx.org