# Ansible Variables

# BIG-IP Provider for BIG-IP Modules
bigips: ["{{ BIGIPhost01 }}"]
bigip_provider:
  server: "{{ item }}"
  user: "{{ BIGIPadminUsername }}"
  password: "{{ BIGIPadminPassword }}"
  validate_certs: false
  no_f5_teem: true

# Use Ansible module or skip
state: 'present'
#state: 'absent'

# Remove AS3 application tenants; NOT common
action: 'deploy'
#action: 'delete'

# AS3 Version Schema
as3_version: '3.47.0'