apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nginx-management-suite'
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmcalalang/lab'
    path: nginx-management-suite/nms-hybrid
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true