# Create or update BIG-IP Device Declarative Onboarding

# BIG-IP BIGIPhost01

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider: "{{ bigip_provider }}"
  delegate_to: localhost
  with_items:
    - "{{ bigips }}"

- name: Get BIG-IP Authentication Token from {{BIGIPhost01}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{BIGIPhost01}}/mgmt/shared/authn/login"
    status_code: "200"
    validate_certs: no
  register: bigip1_auth_response
  retries: 30
  delay: 5
  until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

#- name: Pause for 10 seconds for DO
#  ansible.builtin.pause:
#    seconds: 10

- name: Validate {{BIGIPhost01}} DO Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: GET
    url: "https://{{BIGIPhost01}}/mgmt/shared/declarative-onboarding/available"
    validate_certs: no
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the DO declaration
  template: src="../../do/declarativeOnboarding.template" dest="../../do/declarativeOnboarding.json"
  delegate_to: localhost

- name: Create or update {{ BIGIPhost01 }}; DO Declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','../../do/' + 'declarativeOnboarding.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
#    status_code: [200, 202]
    url: "https://{{BIGIPhost01}}/mgmt/shared/declarative-onboarding"
    validate_certs: no
    timeout: "60"
  register: result
  retries: 30
  delay: 5
  until: "(result.status == 202)"

- name: Delete BIG-IP Authentication Token from {{BIGIPhost01}}
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: DELETE
    url: "https://{{BIGIPhost01}}/mgmt/shared/authz/tokens/{{ bigip1_auth_token }}"
    status_code: "200"
    validate_certs: no
  register: bigip1_token_delete
  retries: 30
  delay: 5
  until: "(bigip1_token_delete is successful) and (bigip1_token_delete.status == 200)"