apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nginx-org'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmcalalang/lab'
    path: services/nginx-org
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-org
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true