apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-headless
  namespace: nginx-ingress
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: nginx-ingress