apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nginx-ingress'
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmcalalang/lab'
    path: nginx-ingress
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true