apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'coffee'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmcalalang/lab'
    path: services/coffee
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true