apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: http.argo.calalang.net
  namespace: argocd
spec:
  ingressClassName: nginx
  host: argo.calalang.net
  tls:
    secret: argo-calalang-net-tls-secret
    redirect:
      enable: true
  upstreams:
  - name: argo-argocd-server
    service: argo-argocd-server
    port: 443
    type: http
    tls:
      enable: true
  routes:
  - path: /
    location-snippets: |
      status_zone argo-argocd-server;
    policies:
    - name: oidc-policy
    action:
      proxy:
        upstream: argo-argocd-server