apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: my-nginx-ingress
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: my-nginx-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginxdemos/nginx-hello:plain-text
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-nginx-ingress
data:
  app.conf: |-
    server {
      listen 8080;

      server_name openshift.calalang.net;

      default_type text/plain;

      location / {
        return 200 "Welcome to pod $hostname. You got here at $date_local!\n" ;
      }
    }