apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: openshift.calalang.net
  namespace: my-nginx-ingress
spec:
  host: openshift.calalang.net
  upstreams:
  - name: www-nginx-org
    service: www-nginx-org
    port: 80
#    healthCheck:
#      enable: true
#      port: 80
#      interval: 20s
#      jitter: 3s
#      fails: 5
#      passes: 5
#      statusMatch: "! 500"
  - name: nginx-app
    service: nginx-app
    port: 80
#    healthCheck:
#      enable: true
#      port: 80
#      interval: 20s
#      jitter: 3s
#      fails: 5
#      passes: 5
#      statusMatch: "! 500"
  routes:
    - path: /
      action:
        proxy:
          upstream: www-nginx-org
          requestHeaders:
            set:
              - name: Host
                value: nginx.org
          responseHeaders:
            add:
              - name: IC-Nginx-Version
                value: ${nginx_version}
                always: true
              - name: IC-Nginx-Host
                value: ${host}
                always: true
              - name: IC-Nginx-URI
                value: ${request_uri}
                always: true
              - name: IC-Nginx-Server-Address
                value: ${server_addr}
                always: true
    - path: /app
      action:
        pass: nginx-app