# Create or update BIG-IP Device; Clustered declaration

# Device 1

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider:
      password: "{{BIGIPadminPassword}}"
      server: "{{deviceName1}}"
      user: "{{BIGIPadminUsername}}"
      validate_certs: no
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName1}}/mgmt/shared/authn/login"
    status_code: "200"
    validate_certs: no
  register: bigip1_auth_response
  retries: 30
  delay: 5
  until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

- name: Validate {{deviceName1}} DO Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: GET
    url: "https://{{deviceName1}}/mgmt/shared/declarative-onboarding/available"
    validate_certs: no
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the DO declaration 1
  template: src="{{ role_path }}/files/do_cluster_bigip1.json" dest="{{ role_path }}/files/{{ deviceName1 }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ deviceName1 }}; DO Declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ deviceName1 }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: POST
    status_code: "202"
    url: "https://{{deviceName1}}/mgmt/shared/declarative-onboarding"
    validate_certs: no
    timeout: "60"

- name: Delete BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip1_auth_token }}"
    method: DELETE
    url: "https://{{deviceName1}}/mgmt/shared/authz/tokens/{{ bigip1_auth_token }}"
    status_code: "200"
    validate_certs: no
  register: bigip1_token_delete
  retries: 30
  delay: 5
  until: "(bigip1_token_delete is successful) and (bigip1_token_delete.status == 200)"

- name: Wait for Sync to happen or race condition will occur
  pause:
    seconds: 200

# Device 2

- name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
  bigip_wait:
    timeout: 300
    provider:
      password: "{{BIGIPadminPassword}}"
      server: "{{deviceName1}}"
      user: "{{BIGIPadminUsername}}"
      validate_certs: no
  delegate_to: localhost

- name: Get BIG-IP Authentication Token from {{deviceName2}}
  delegate_to: localhost
  uri:
    body: '{"username":"{{BIGIPadminUsername}}","password":"{{BIGIPadminPassword}}","loginProviderName":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{deviceName2}}/mgmt/shared/authn/login"
    status_code: "200"
    validate_certs: no
  register: bigip2_auth_response
  retries: 30
  delay: 5
  until: "(bigip2_auth_response is successful) and (bigip2_auth_response.status == 200)"

- name: Assign Auth Token to Variable
  set_fact:
    bigip2_auth_token: "{{ bigip2_auth_response.json.token.token }}"

- name: Validate {{deviceName2}} DO Rest Worker is ready
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: GET
    url: "https://{{deviceName2}}/mgmt/shared/declarative-onboarding/available"
    validate_certs: no
  retries: 30
  delay: 5
  register: result
  until: "(result is successful) and (result.status == 200)"

- name: Prepare the DO declaration 2
  template: src="{{ role_path }}/files/do_cluster_bigip2.json" dest="{{ role_path }}/files/{{ deviceName2 }}_declaration.json"
  delegate_to: localhost

- name: Create or update {{ deviceName2 }}; DO Declaration
  delegate_to: localhost
  uri:
    body: "{{ lookup('file','{{ role_path }}/files/' + '{{ deviceName2 }}_declaration.json') }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: POST
    status_code: "202"
    url: "https://{{deviceName2}}/mgmt/shared/declarative-onboarding"
    validate_certs: no
    timeout: "60"

- name: Delete BIG-IP Authentication Token from {{deviceName1}}
  delegate_to: localhost
  uri:
    headers:
      X-F5-Auth-Token: "{{ bigip2_auth_token }}"
    method: DELETE
    url: "https://{{deviceName2}}/mgmt/shared/authz/tokens/{{ bigip2_auth_token }}"
    status_code: "200"
    validate_certs: no
  register: bigip2_token_delete
  retries: 30
  delay: 5
  until: "(bigip2_token_delete is successful) and (bigip2_token_delete.status == 200)"

- name: Wait for Sync to happen or race condition will occur
  pause:
    seconds: 200