name: Lab Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "BIG-IP Automation Toolchain"
  BIG-IP:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2   

      - name: Install PIP
        run: sudo apt-get install -y python3-pip

      - name: Install apt-get dependencies
        run: sudo pip3 install jmespath

      - name: Setup ansible
        run: |
          ansible --version
          pipx inject ansible-core jmespath

      # - name: Run ansible-lint
      #   # replace `main` with any valid ref, or tags like `v6`
      #   uses: ansible-community/ansible-lint-action@main
      #   # optional:
      #   with:
      #     path: "./ansible/playbooks/"  # <-- only one value is allowed   

      - name: Run Ansible Playbooks
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --extra-vars "@../defaults/main.yaml"
          #  --verbose -vvvv
          # Required, playbook filepath
          playbook: "toolchain_declarations.yaml"
          # Optional, directory where playbooks live
          directory: "./ansible/playbooks"

  F5XC:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment Variables
    env:
      VES_P12_PASSWORD: "Harrison123!"

    # Where are the Terraform files
    defaults:
      run:
        working-directory: distributed-cloud

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Download Terraform State
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: f5xc-terraform-state
        # Optional, a directory where to extract artifact(s), defaults to the current directory
        path: ./
        # Optional, defaults to current repo
        check_artifacts:  false
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        search_artifacts: false
        # Optional, choose to skip unpacking the downloaded artifact(s)
        # default false
        skip_unpack: false
        # Optional, choose how to exit the action if no artifact is found
        # can be one of:
        #  "fail", "warn", "ignore"
        # default fail
        if_no_artifact_found: fail

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false

    - name: Terraform Import
      id: import
      run: terraform import

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false

    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve

    - name: Upload Terraform State
      uses: actions/upload-artifact@v3
      with:
        name: f5xc-terraform-state
        path: distributed-cloud/terraform.tfstate
        retention-days: 30