{{- if .Values.nic.enabled }}
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: {{ template "nic.nms.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.nic.ingressClassName }}
  http-snippets: {{- toYaml .Values.nic.httpSnippets | indent 2 }}
  host: {{ template "nic.nms.host" . }}
  tls:
    secret: {{ template "nms.apigw.secret-name" . }}
    redirect:
      enable: true
  server-snippets: {{- toYaml .Values.nic.serverSnippets | indent 2 }}
  upstreams:
    - name: {{ template "nms.apigw.name" . }}
      service: {{ template "nms.apigw.name" . }}
      port: {{ template "nms.apigw.port" . }}
      type: http
      tls:
        enable: true
    {{- include "nic.nms.userUpstreams" . | nindent 4 }}
  {{- with .Values.nic.routes }}
  routes:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
  {{- with .Values.nic.policies }}
  policies:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
{{- end }}
